[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints= {sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/9aOanwEx_Z-TIA2PgWWZzd6WxJO1KBKY", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/9aOanwEx_Z-TIA2PgWWZzd6WxJO1KBKY"}
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@ccip/=lib/ccip/',
    '@chainlink/=lib/chainlink/',
    '@chainlink/local/=lib/chainlink-local/',
]

[invariant]
runs = 128
depth = 128
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
